// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: pb/game.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameServiceClient interface {
	PlayerInfo(ctx context.Context, opts ...grpc.CallOption) (GameService_PlayerInfoClient, error)
	GameInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (GameService_GameInfoClient, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) PlayerInfo(ctx context.Context, opts ...grpc.CallOption) (GameService_PlayerInfoClient, error) {
	stream, err := c.cc.NewStream(ctx, &GameService_ServiceDesc.Streams[0], "/gamePb.GameService/PlayerInfo", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameServicePlayerInfoClient{stream}
	return x, nil
}

type GameService_PlayerInfoClient interface {
	Send(*Player) error
	Recv() (*Player, error)
	grpc.ClientStream
}

type gameServicePlayerInfoClient struct {
	grpc.ClientStream
}

func (x *gameServicePlayerInfoClient) Send(m *Player) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gameServicePlayerInfoClient) Recv() (*Player, error) {
	m := new(Player)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gameServiceClient) GameInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (GameService_GameInfoClient, error) {
	stream, err := c.cc.NewStream(ctx, &GameService_ServiceDesc.Streams[1], "/gamePb.GameService/GameInfo", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameServiceGameInfoClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GameService_GameInfoClient interface {
	Recv() (*Info, error)
	grpc.ClientStream
}

type gameServiceGameInfoClient struct {
	grpc.ClientStream
}

func (x *gameServiceGameInfoClient) Recv() (*Info, error) {
	m := new(Info)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GameServiceServer is the server API for GameService service.
// All implementations must embed UnimplementedGameServiceServer
// for forward compatibility
type GameServiceServer interface {
	PlayerInfo(GameService_PlayerInfoServer) error
	GameInfo(*Empty, GameService_GameInfoServer) error
	mustEmbedUnimplementedGameServiceServer()
}

// UnimplementedGameServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGameServiceServer struct {
}

func (UnimplementedGameServiceServer) PlayerInfo(GameService_PlayerInfoServer) error {
	return status.Errorf(codes.Unimplemented, "method PlayerInfo not implemented")
}
func (UnimplementedGameServiceServer) GameInfo(*Empty, GameService_GameInfoServer) error {
	return status.Errorf(codes.Unimplemented, "method GameInfo not implemented")
}
func (UnimplementedGameServiceServer) mustEmbedUnimplementedGameServiceServer() {}

// UnsafeGameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameServiceServer will
// result in compilation errors.
type UnsafeGameServiceServer interface {
	mustEmbedUnimplementedGameServiceServer()
}

func RegisterGameServiceServer(s grpc.ServiceRegistrar, srv GameServiceServer) {
	s.RegisterService(&GameService_ServiceDesc, srv)
}

func _GameService_PlayerInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GameServiceServer).PlayerInfo(&gameServicePlayerInfoServer{stream})
}

type GameService_PlayerInfoServer interface {
	Send(*Player) error
	Recv() (*Player, error)
	grpc.ServerStream
}

type gameServicePlayerInfoServer struct {
	grpc.ServerStream
}

func (x *gameServicePlayerInfoServer) Send(m *Player) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gameServicePlayerInfoServer) Recv() (*Player, error) {
	m := new(Player)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GameService_GameInfo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GameServiceServer).GameInfo(m, &gameServiceGameInfoServer{stream})
}

type GameService_GameInfoServer interface {
	Send(*Info) error
	grpc.ServerStream
}

type gameServiceGameInfoServer struct {
	grpc.ServerStream
}

func (x *gameServiceGameInfoServer) Send(m *Info) error {
	return x.ServerStream.SendMsg(m)
}

// GameService_ServiceDesc is the grpc.ServiceDesc for GameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gamePb.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PlayerInfo",
			Handler:       _GameService_PlayerInfo_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GameInfo",
			Handler:       _GameService_GameInfo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pb/game.proto",
}
